apiVersion: v1
kind: Service
metadata:
  name: pandax
  labels:
    app.kubernetes.io/name: pandax
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: pandax
