apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: pandax
    app.kubernetes.io/version: 1.0.0
  name: pandax
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pandax
    app.kubernetes.io/version: 1.0.0
  name: pandax
  namespace: pandax
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pandax
    app.kubernetes.io/version: 1.0.0
  name: pandax-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: pandax
  namespace: pandax
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pandax
    app.kubernetes.io/version: 1.0.0
  name: pandax
  namespace: pandax
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: pandax
    app.kubernetes.io/version: 1.0.0
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pandax
    app.kubernetes.io/version: 1.0.0
  name: pandax
  namespace: pandax
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pandax
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pandax
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - image: xmadmin/pandax:v1.4
        imagePullPolicy: Always
        name: pandax
        ports:
        - containerPort: 7788
          name: http
          protocol: TCP
      serviceAccountName: pandax
