# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      fail-fast: false
      #     max-parallel: 2
      matrix:
        version: ["ms-chat"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"
    # Login cn-hangzhou
    - name: Login Into HangZhou
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: "registry.cn-hangzhou.aliyuncs.com"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build And Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        file: Dockerfile
        tags: |
          registry.cn-hangzhou.aliyuncs.com/okami/docker-php:${{ matrix.version }}
          registry.cn-hangzhou.aliyuncs.com/okami/docker-php:${{ matrix.version }}-${{ steps.date.outputs.today }}
